apps/prepo-docs/README.md

Should trigger a build on vercel only on prepo-docs

fix: rename title on readme

---

apps/prepo-simulator/README.md

This should only trigger a preview build for `prepo-simulator` app on Vercel

fix: test change on prepo-simulator

---

apps/frontend/acquisition-royale-home/src/pages/_app.tsx
apps/frontend/acquisition-royale-home/src/pages/_document.tsx
apps/frontend/acquisition-royale-home/src/pages/_error.tsx
apps/frontend/acquisition-royale-home/src/pages/api/tunnel.ts
apps/frontend/acquisition-royale-home/src/pages/icons.tsx
apps/frontend/acquisition-royale-home/src/pages/index.tsx
apps/frontend/acquisition-royale-home/src/styles/default.css
apps/frontend/acquisition-royale-home/styled.d.ts

pages, styles
https://www.notion.so/Migrate-prepo-acquisition-royale-fe-private-repository-to-monorepo-18829a9ef30a40e989dc4034eb61fed7

feat: acquisition royale pages

---

apps/frontend/acquisition-royale-home/global.d.ts
apps/frontend/acquisition-royale-home/next-env.d.ts
apps/frontend/acquisition-royale-home/next-sitemap.js
apps/frontend/acquisition-royale-home/next.config.js
apps/frontend/acquisition-royale-home/package.json
apps/frontend/acquisition-royale-home/src/pages/_app.tsx
apps/frontend/acquisition-royale-home/src/pages/_document.tsx
apps/frontend/acquisition-royale-home/src/pages/_error.tsx
apps/frontend/acquisition-royale-home/src/pages/api/tunnel.ts
apps/frontend/acquisition-royale-home/src/pages/icons.tsx
apps/frontend/acquisition-royale-home/src/pages/index.tsx
apps/frontend/acquisition-royale-home/src/styles/default.css
apps/frontend/acquisition-royale-home/styled.d.ts
turbo.json
yarn.lock

next config files, done!
- tested build locally
- tested dev server working
https://www.notion.so/Migrate-prepo-acquisition-royale-fe-private-repository-to-monorepo-18829a9ef30a40e989dc4034eb61fed7

feat: acquisition royale next config

---

apps/frontend/acquisition-royale-home/src/components/MainTab.tsx
apps/frontend/acquisition-royale-home/src/features/mvp/GamePage.tsx

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=2533aafbdb5d4c82aa64920107f82a05

feat: acquisition royale UI improvements

---

apps/frontend/website/src/pages/_app.tsx

feat: website test change

---

apps/frontend/website/src/pages/_app.tsx

feat: test deployments website

---

apps/frontend/website/src/pages/_app.tsx

Testing deployment 6th on website

feat: test deployment website

---

apps/frontend/website/src/pages/_app.tsx

Testing deployments on website 9th

feat: test deployments on website

---

apps/frontend/acquisition-royale-home/vercel.json
apps/frontend/website/src/pages/_app.tsx

- Will trigger a re-deploy to website
- Will remove the vercel bot from `acquisition-royale-home`

feat: remove comment from website

---

apps/smart-contracts/core/contracts/mocks/MockStrategy.sol
apps/smart-contracts/core/deploy/MockStrategy.ts
apps/smart-contracts/core/test/MockStrategy.test.ts
apps/smart-contracts/core/test/SingleStrategyController.test.ts

Move https://github.com/prepo-io/prepo-core-private/pull/187 to monorepo

feat: move pr 187

---

apps/smart-contracts/core/contracts/mocks/MockStrategy.sol
apps/smart-contracts/core/deploy/Collateral.ts
apps/smart-contracts/core/deploy/MockBaseToken.ts
apps/smart-contracts/core/deploy/MockStrategy.ts
apps/smart-contracts/core/deploy/SingleStrategyController.ts
apps/smart-contracts/core/test/MockStrategy.test.ts
apps/smart-contracts/core/test/SingleStrategyController.test.ts

Move https://github.com/prepo-io/prepo-core-private/pull/186 to monorepo

feat: move pr 186

---

apps/frontend/acquisition-royale-home/src/components/layout/Footer.tsx
apps/frontend/acquisition-royale-home/src/components/layout/Header.tsx
apps/frontend/acquisition-royale-home/src/components/layout/Layout.tsx

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=70a0196d1e4947228c12d6b01d246746

fix: background shade changes because of page height

---

apps/frontend/acquisition-royale-home/public/assets/nft-placeholder.svg
apps/frontend/acquisition-royale-home/src/components/EnterpriseCard.tsx
apps/frontend/acquisition-royale-home/src/components/EnterpriseCarousel.tsx
apps/frontend/acquisition-royale-home/src/components/Input.tsx
apps/frontend/acquisition-royale-home/src/components/LoadingCarouselCard.tsx
apps/frontend/acquisition-royale-home/src/features/mvp/Competition.tsx
apps/frontend/acquisition-royale-home/src/features/mvp/SearchCompetition.tsx
apps/frontend/acquisition-royale-home/src/features/mvp/actions/Revive.tsx
apps/frontend/acquisition-royale-home/src/stores/AcquisitionRoyaleContractStore.ts
apps/frontend/acquisition-royale-home/src/stores/CompetitionStore.ts
scripts/changedApps.ts

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=b19477d57a094c63a91a4b5093fb8ba1

feat: random enterprises

---

apps/frontend/core-dapp/package.json
apps/frontend/core-dapp/src/lib/config.ts
apps/frontend/core-dapp/src/pages/_app.tsx
yarn.lock

https://www.notion.so/Add-panelbear-analytics-f9e4215a61f1445586f90dc2e75f22b2

feat: add panelbear to core dapp

---

apps/frontend/acquisition-royale-home/next.config.js
apps/frontend/acquisition-royale-home/package.json
apps/frontend/acquisition-royale-home/src/features/mvp/acquire/AcquireStore.ts
apps/frontend/acquisition-royale-home/src/features/mvp/merge/MergeStore.ts
apps/frontend/acquisition-royale-home/src/hooks/useCountdown.ts
apps/frontend/acquisition-royale-home/src/lib/supported-contracts.ts
apps/frontend/acquisition-royale-home/src/stores/utils/enterprise-utils.ts
apps/frontend/acquisition-royale-home/src/stores/utils/stores-config.ts
apps/frontend/acquisition-royale-home/src/utils/common-utils.ts

https://www.notion.so/Migrate-acquisition-royale-home-to-use-migrated-prepo-constants-package-afe32817353e4641ab518512b9e29543

feat: use prepo-constants on acquisition-royale-home

---

packages/prepo-utils/package.json
yarn.lock

Fixes issues with building other apps using this package on vercel

fix: prepo utils build

---

apps/frontend/core-dapp/src/features/deposit/DepositTransactionSummary.tsx

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=35dcf02f76284d8e8efe0b67f7a04234&p=92f33df7e6cd48c2a370b42c8cf4eeba

fix: correct deposit fee

---

apps/frontend/core-dapp/package.json

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=07dea34824ae40bb88ca66da75fdcf5e

fix: reduce sentry captured issues

---

apps/frontend/core-dapp/src/components/LiquidityChartRangeInput/Chart.tsx
apps/frontend/core-dapp/src/components/MarketCard.tsx
apps/frontend/core-dapp/src/features/liquidity/LiquidityPage.tsx
apps/frontend/core-dapp/src/features/market-overview/MarketDataColumn.tsx
apps/frontend/core-dapp/src/features/market-overview/market-utils.ts
apps/frontend/core-dapp/src/utils/__tests__/number-utils.test.ts
apps/frontend/core-dapp/src/utils/number-utils.ts
apps/frontend/core-dapp/src/utils/numberFormatter.ts
yarn.lock

Completes https://github.com/prepo-io/prepo-core-dapp-fe-private/pull/409

feat: show significant figures

---

apps/frontend/core-dapp/src/utils/market-utils.ts

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=35dcf02f76284d8e8efe0b67f7a04234&p=6671209a11dc4ea9b36e29f985eb844a

fix: bug with trimmed props

---

apps/frontend/core-dapp/src/components/SettingsMenu.tsx

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=1e5003a5a0f740598189a061cbba6452

feat: keep dropdown menu when change

---

apps/frontend/core-dapp/jest.config.ts
apps/frontend/core-dapp/tsconfig.json
apps/frontend/react-boilerplate/jest.config.ts
apps/frontend/website/jest.config.ts
packages/config/jest-common.js
packages/config/jest-frontend.js
packages/tsconfig/frontend.json
yarn.lock

https://www.notion.so/Migrate-tsconfig-and-jest-config-on-core-dApp-monorepo-f26df3f1a6b54cfe9c084626994a2689

fix: tsconfig and jestconfig on coredapp

---

.github/workflows/size-label.yml

https://www.notion.so/Add-Github-labels-based-on-diff-size-f436117c7150458aba121228127bf866

feat: add github labels to pr size

---

.gitignore
packages/constants/src/gas.ts
packages/prepo-stores/src/GasStore.ts

https://www.notion.so/eb96722b397d42c9908002ca06af88e3?v=1f519ba1849347aa9740faedda4acf3b&p=4e6e0eecdda24ceb8eed1ca3c9f9897b

feat: update gas speed options

---

apps/frontend/core-dapp/src/components/Link.tsx
apps/frontend/core-dapp/src/features/position/PositionItem.tsx
yarn.lock

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=57acdc43fe894101a18c4aa66daff42a

feat: clickable position

---

packages/prepo-stores/src/utils/error-capturer-util.ts
packages/prepo-utils/src/makeError.ts

https://www.notion.so/Better-error-handling-on-core-dApp-e6ed4467440d497d96070c1e1719c540

feat: user friendly error messages

---

apps/subgraphs/core-dapp/.eslintrc.js
apps/subgraphs/core-dapp/package.json
apps/subgraphs/core-dapp/src/mappings/accounting.ts
apps/subgraphs/core-dapp/src/mappings/core.ts
apps/subgraphs/core-dapp/src/types/position.ts
yarn.lock

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=df2fbe5d103d44cf96c258e01ea39362

feat: subgraph minor refactor

---

apps/subgraphs/core-dapp/.eslintrc.js
apps/subgraphs/core-dapp/package.json
apps/subgraphs/core-dapp/schema.graphql
apps/subgraphs/core-dapp/src/mappings/accounting.ts
apps/subgraphs/core-dapp/src/mappings/core.ts
apps/subgraphs/core-dapp/src/mappings/factory.ts
apps/subgraphs/core-dapp/src/types/position.ts
yarn.lock

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=6e540455a3194beaaffcc5c4b57e7cbc

fix: collateral validity change

---

apps/subgraphs/core-dapp/src/mappings/core.ts
apps/subgraphs/core-dapp/src/mappings/transaction.ts
apps/subgraphs/core-dapp/src/utils/constants.ts

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=6f2fac3cc92d42219a233528dcd35766

feat: subgraph track long short token transfer

---

apps/subgraphs/core-dapp/schema.graphql
apps/subgraphs/core-dapp/src/mappings/core.ts
apps/subgraphs/core-dapp/src/mappings/factory.ts
apps/subgraphs/core-dapp/src/mappings/transaction.ts
apps/subgraphs/core-dapp/src/utils/constants.ts
apps/subgraphs/core-dapp/subgraph.yaml

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=af789c3796744a13a6f44ae4794df410

fix: graphql schema comment

---

apps/frontend/core-dapp/src/features/portfolio/PortfolioStore.ts
apps/frontend/core-dapp/src/features/position/ClosePositionSummary.tsx
apps/frontend/core-dapp/src/features/position/PositionItem.tsx

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=491e7aaaeeb945c99c20b46e93b943da
`PNL percentage in position item`
`Estimated PNL in close position modal`

feat: frontend pnl percentage

---

apps/subgraphs/core-dapp/package.json
apps/subgraphs/core-dapp/schema.graphql
apps/subgraphs/core-dapp/src/mappings/core.ts
apps/subgraphs/core-dapp/src/mappings/factory.ts
apps/subgraphs/core-dapp/src/mappings/transaction.ts
apps/subgraphs/core-dapp/subgraph.yaml

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=f72d27dcd84a4e22ba572c08898bd443

feat: track relevant transfer event of base token

---

apps/frontend/core-dapp/src/features/portfolio/PortfolioStore.ts
apps/frontend/core-dapp/src/graphql/core-dapp.graphql
apps/frontend/core-dapp/src/stores/graphs/queries/core.queries.ts
apps/frontend/core-dapp/src/types/user.types.ts
packages/prepo-constants/src/graphs.ts

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=acede37e25074aeb85084f4ff071d786

feat: temporarily use staging subgraph until main subgraph synced

---

apps/subgraphs/core-dapp/src/mappings/transaction.ts
apps/subgraphs/core-dapp/src/utils/constants.ts
apps/subgraphs/core-dapp/src/utils/transactions.ts

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=4dd946279212432d947a702cd058dedd

feat: subgraph event withdraw

---

apps/subgraphs/core-dapp/.eslintrc.js
apps/subgraphs/core-dapp/schema.graphql
apps/subgraphs/core-dapp/src/mappings/transaction.ts
apps/subgraphs/core-dapp/src/utils/constants.ts
apps/subgraphs/core-dapp/src/utils/transactions.ts
yarn.lock

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=f72d27dcd84a4e22ba572c08898bd443

feat: check if a transaction is deposit

---

.github/labeler.yml

https://www.notion.so/Add-labels-to-smart-contracts-token-app-on-github-898005c44aae4ba89fa54817023073e6

feat: add github labels to smart-contracts token app

---

apps/smart-contracts/core/tsconfig.json
apps/smart-contracts/token/index.ts
apps/smart-contracts/token/tsconfig.json
packages/prepo-shared-contracts/tsconfig.json
packages/tsconfig/smart-contracts.json

https://www.notion.so/Refactor-tsconfig-for-smart-contract-applications-on-the-monorepo-bac563c53c2b4abc88a5d31cb70236e2

feat: refactor tsconfig smart contracts

---

.github/workflows/deploy-production-apps.yml

https://www.notion.so/Fix-deploy-to-production-pipeline-for-frontend-projects-when-smart-contract-project-is-changed-52b33266a80d4365b205a7f447da5dbb

feat: improve deploy prod pipeline

---

apps/smart-contracts/core/.solhint.json
apps/smart-contracts/core/package.json
apps/smart-contracts/token/.solhint.json
apps/smart-contracts/token/package.json
packages/prepo-shared-contracts/.solhint.json
packages/prepo-shared-contracts/package.json
packages/solhint-config-prepo/index.js
packages/solhint-config-prepo/package.json
yarn.lock

https://www.notion.so/Investigate-if-solhint-configuration-file-can-be-shared-988a23e096fb43828da8e40d390a8dac

feat: add shared solhint config

---

apps/frontend/core-dapp/package.json
apps/subgraphs/boilerplate/package.json
apps/subgraphs/core-dapp/package.json
packages/config/package.json

https://www.notion.so/Remove-license-key-field-from-package-jsons-582a008cb87c4d85b8d7b97fab509e62

fix: remove package json license keys

---

LICENSE
package.json

https://www.notion.so/Fix-monorepo-licence-458a77d1ca534710b2fc74a72e8beab7

fix: license to specify agpl3

---

apps/subgraphs/core-dapp/src/mappings/transaction.ts
apps/subgraphs/core-dapp/src/utils/constants.ts
apps/subgraphs/core-dapp/src/utils/transactions.ts

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=b38f665830f4411d8b23a2c1dea6e9f4

feat: subgraph event close

---

apps/subgraphs/core-dapp/src/mappings/transaction.ts
apps/subgraphs/core-dapp/src/utils/constants.ts
apps/subgraphs/core-dapp/src/utils/transactions.ts

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=e40e5b0196be4f109f490e72e8cfebe6

feat: conditions check for opening trade

---

apps/smart-contracts/token/contracts/PPO.sol
apps/smart-contracts/token/test/PPO.test.ts
apps/smart-contracts/token/test/fixtures/PPOFixtures.ts
packages/prepo-shared-contracts/contracts/SafeOwnableUpgradeable.sol
packages/prepo-shared-contracts/contracts/mock/DeployableSafeOwnableUpgradeable.sol
packages/prepo-shared-contracts/test/SafeOwnableUpgradeable.test.ts
packages/prepo-shared-contracts/test/fixtures/DeployableSafeOwnableUpgradeableFixture.ts
packages/prepo-shared-contracts/test/fixtures/SafeOwnableUpgradeableFixture.ts

* Adding relevant files for PPO contract
* Also added overwritten function signature of `IPPO.sol` to avoid making the contract abstract as all those methods were already defined on `IPPO.sol` beforehand.

feat: adding relevant files for PPO

---

apps/smart-contracts/core/.env.example
apps/smart-contracts/core/README.md
apps/smart-contracts/core/hardhat.config.ts
apps/smart-contracts/core/package.json
apps/smart-contracts/core/tsconfig.json
apps/smart-contracts/token/hardhat.config.ts
apps/smart-contracts/token/package.json
package.json
packages/prepo-constants/src/networks.ts
packages/prepo-hardhat/src/generateHardhatConfig.ts
packages/prepo-hardhat/src/generateHardhatLocalConfig.ts
packages/prepo-hardhat/src/smart-contracts-utils.ts
packages/tsconfig/package.json
yarn.lock

https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?v=177bee72a49349b7b5af7c370371389e&p=589fd4716aac4ad2bd417ca05bdb925b

feat: changes for deployment of PrePOMarketFactory on polygon
