prepo-io/prepo-monorepo

apps/frontend/acquisition-royale-home/src/components/EnterpriseCard.tsx, apps/frontend/acquisition-royale-home/src/components/EnterpriseCarousel.tsx, apps/frontend/acquisition-royale-home/src/components/LoadingCarouselCard.tsx, apps/frontend/acquisition-royale-home/src/components/MainTab.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/ActionCard.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/ActionsStore.ts, apps/frontend/acquisition-royale-home/src/features/mvp/Competition.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/GamePage.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/MyEnterprises.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/SearchCompetition.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/acquire/Acquire.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/acquire/AcquireStore.ts, apps/frontend/acquisition-royale-home/src/features/mvp/actions/Compete.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/actions/DepositRp.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/actions/Rename.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/actions/Revive.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/actions/WithdrawRp.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/merge/Merge.tsx, apps/frontend/acquisition-royale-home/src/features/mvp/merge/MergeStore.ts, apps/frontend/acquisition-royale-home/src/features/mvp/stores/RpShopStore.ts, apps/frontend/acquisition-royale-home/src/stores/AcquisitionRoyaleContractStore.ts, apps/frontend/acquisition-royale-home/src/stores/CompeteV1ContractStore.ts, apps/frontend/acquisition-royale-home/src/stores/CompetitionStore.ts, apps/frontend/acquisition-royale-home/src/stores/EnterprisesStore.ts, apps/frontend/acquisition-royale-home/src/stores/RootStore.ts, apps/frontend/acquisition-royale-home/src/stores/SignerStore.ts, apps/frontend/acquisition-royale-home/src/types/enterprise.types.ts
https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=ca0ef4b10dcf4e10b17a0ff06e6a0246
https://www.notion.so/FE-Project-Management-d3878c29e9534234a50f4f8838525bee?p=963684290dc04fe9b669e1ee71947db7
Changes
- simplified EnterpriseCard (no more glowing, no more clicking)
- refactored EnterprisesStore, moved signer related stuffs to SignerStore (e.g. signerEnterprises, signerActiveEnterprise), and competition related stuffs to CompetitionStore (e.g. competitionEnterprises, competitionActiveEnterprise)
- simplified lazyLoading algorithm: previously it was not using proper "observable approach", values were loaded in autorun, and updated via a property like `signerEnterprises` and `competitionEnterprises`. Now `signerEnterprises` and `competitionEnterprises` are …
=> feat: acquisition royale enterprises carousel

apps/smart-contracts/core/harnesses/PrePO.ts, apps/smart-contracts/core/helpers/index.ts, apps/smart-contracts/core/package.json, apps/smart-contracts/core/utils/index.ts
This harness is for tasks and scripts to access existing deployments of a core stack, depending on the chain specified.
The `helpers` file has been modified to add a function to fetch an existing `PrePOMarketFactory`. Previously there was only one to obtain an existing `Collateral` contract. I have separated out most of the logic into a generalized function to avoid repeat code. These functions are needed because `Collateral` and `PrePOMarketFactory` are upgradeable and do not utilize `hardhat-deploy`.
I had to disable `no-explicit-any` linting around the `MarketAdded` event fixture because the `TypedEvent` type returned by the event filter contains `any` within the type. I did not continue to try and figure out a workaround to save time.
The `utils` file has been updated with constants …
=> feat: added PrePO harness to manage deployments for tasks utilities

apps/frontend/acquisition-royale-home/src/stores/CompetitionStore.ts
Added filtering for immune or owned enterprises
Currently when ID of owned enterprises is searched, it will show content for no enterprise found. Which is also wrong because ideally we want to show only enterprises the user can acquire.
=> fix: prevent searching immuned or owned enterprises

apps/frontend/website/src/components/layout/Footer.tsx
https://www.notion.so/Copyright-year-should-be-2022-in-website-footer-7944ab2adb974cacac6cc0727e7ef79b
=> fix: use fullyear instead of hardcoded year

apps/frontend/core-dapp/src/components/Table.tsx, apps/frontend/core-dapp/src/components/charts/FloatingCard.tsx, apps/frontend/core-dapp/src/features/history/HistoryItemDesktop.tsx, apps/frontend/core-dapp/src/features/history/HistoryItemMobile.tsx, apps/frontend/core-dapp/src/features/market-overview/MarketChart.tsx, apps/frontend/core-dapp/src/features/portfolio/Portfolio.tsx, apps/frontend/core-dapp/src/features/portfolio/PortfolioBreakdownItem.tsx, apps/frontend/core-dapp/src/features/position/PositionItem.tsx, apps/frontend/core-dapp/src/features/trade/EstimateProfitLoss.tsx, apps/frontend/core-dapp/src/stores/CollateralStore.ts, apps/frontend/core-dapp/src/utils/__tests__/numberFormatter.test.ts, apps/frontend/core-dapp/src/utils/number-utils.ts, apps/frontend/core-dapp/src/utils/numberFormatter.ts
https://www.notion.so/Normalize-only-1-2-util-functions-to-handle-number-formatting-across-the-app-e52b2469c7dd470eaa7fa890e6fda841
Removes `formatUsd` from the app. We can now use `numberFormatter.toUsd()`
=> feat: add toUsd function

apps/frontend/core-dapp/src/components/Table.tsx, apps/frontend/core-dapp/src/components/charts/FloatingCard.tsx, apps/frontend/core-dapp/src/features/delegate/DelegateCard.tsx, apps/frontend/core-dapp/src/features/history/HistoryItemDesktop.tsx, apps/frontend/core-dapp/src/features/history/HistoryItemMobile.tsx, apps/frontend/core-dapp/src/features/market-overview/MarketChart.tsx, apps/frontend/core-dapp/src/features/portfolio/Portfolio.tsx, apps/frontend/core-dapp/src/features/portfolio/PortfolioBreakdownItem.tsx, apps/frontend/core-dapp/src/features/position/PositionItem.tsx, apps/frontend/core-dapp/src/features/trade/EstimateProfitLoss.tsx, apps/frontend/core-dapp/src/stores/CollateralStore.ts, apps/frontend/core-dapp/src/utils/__tests__/number-utils.test.ts, apps/frontend/core-dapp/src/utils/__tests__/numberFormatter.test.ts, apps/frontend/core-dapp/src/utils/number-utils.ts, apps/frontend/core-dapp/src/utils/numberFormatter.ts
https://www.notion.so/Normalize-only-1-2-util-functions-to-handle-number-formatting-across-the-app-e52b2469c7dd470eaa7fa890e6fda841
Removes `numberWithCommas` from the app. We can now use `numberFormatter.withCommas()`
=> feat: add withComas function

apps/frontend/core-dapp/src/components/AdvancedSettingsModal/AdvancedSettingsModal.tsx, apps/frontend/core-dapp/src/components/Percent.tsx, apps/frontend/core-dapp/src/components/Table.tsx, apps/frontend/core-dapp/src/components/charts/FloatingCard.tsx, apps/frontend/core-dapp/src/features/delegate/DelegateCard.tsx, apps/frontend/core-dapp/src/features/history/HistoryItemDesktop.tsx, apps/frontend/core-dapp/src/features/history/HistoryItemMobile.tsx, apps/frontend/core-dapp/src/features/market-overview/MarketChart.tsx, apps/frontend/core-dapp/src/features/market-overview/MarketDataColumn.tsx, apps/frontend/core-dapp/src/features/portfolio/Portfolio.tsx, apps/frontend/core-dapp/src/features/portfolio/PortfolioBreakdownItem.tsx, apps/frontend/core-dapp/src/features/position/PositionItem.tsx, apps/frontend/core-dapp/src/features/trade/EstimateProfitLoss.tsx, apps/frontend/core-dapp/src/stores/CollateralStore.ts, apps/frontend/core-dapp/src/utils/__tests__/number-utils.test.ts, apps/frontend/core-dapp/src/utils/__tests__/numberFormatter.test.ts, apps/frontend/core-dapp/src/utils/number-utils.ts, apps/frontend/core-dapp/src/utils/numberFormatter.ts
https://www.notion.so/Normalize-only-1-2-util-functions-to-handle-number-formatting-across-the-app-e52b2469c7dd470eaa7fa890e6fda841
Removes `formatPercentage` from the app. We can now use `numberFormatter.percentage()` or `numberFormatter.rawPercentage()` for those cases
=> feat: use numberFormatter for percentages

apps/frontend/core-dapp/src/components/Percent.tsx
https://www.notion.so/Fix-showing-red-percentage-on-Estimated-PnL-slider-label-when-it-s-positive-895d9a2c27874feeba604f6ffca7fffc
=> fix: percentage label color

apps/frontend/core-dapp/src/features/portfolio/Portfolio.tsx, apps/frontend/core-dapp/src/features/portfolio/PortfolioBreakdownItem.tsx
https://www.notion.so/Portfolio-breakdown-table-is-not-matching-design-on-mobile-7625c1e03ce54a56b530972c5233ec15
Note: the font-size on Portfolio Breakdown has increased on desktop view. This is due to the consistency that the `Typography` component fixes on the responsiveness of our texts. This doesn't really match 1:1 to the design on figma but it's consistent and it looks good.
=> fix: portfolio breakdown mobile design

apps/smart-contracts/token/contracts/TokenShop.sol, apps/smart-contracts/token/contracts/interfaces/ITokenShop.sol, apps/smart-contracts/token/test/TokenShop.test.ts
* Resubmitting [PR 142](https://github.com/prepo-io/prepo-token-contracts-private/pull/142) from Token-contracts repo for adding a method to withdraw any external ERC20 token deposited into the TokenShop contract.
* This PR was already LGTMd by @ramenforbreakfast 
* The ERC20 token can only be withdrawn by the owner.
=> feat: adding withdrawERC20 token in tokenShop

apps/smart-contracts/token/contracts/TokenShop.sol, apps/smart-contracts/token/contracts/interfaces/ITokenShop.sol, apps/smart-contracts/token/test/TokenShop.test.ts
* Resubmitting [PR 143](https://github.com/prepo-io/prepo-token-contracts-private/pull/143) from Token-contracts repo for adding a method to withdraw any external ERC721 or ERC1155 token deposited into the TokenShop contract.
* This PR was already LGTMd by @ramenforbreakfast 
* The ERC721 and ERC1155 token can only be withdrawn by the owner.
=> feat: added methods to withdraw ERC721 and ERC1155 from Token Shop

apps/subgraphs/core-dapp/src/utils/transactions.ts
Importing ZERO_ADDRESS from 'prepo-constants' package is causing build to fail. I think this is because subgraphs build with AssemblyScript and AssemblyScript doesn't understand our javascript packages local linking?
=> fix: import from constants instead of package

apps/smart-contracts/token/contracts/interfaces/IPPO.sol, apps/smart-contracts/token/contracts/interfaces/ITransferHook.sol
* Adding `IPPO` and `ITransferHook` interfaces.
* Did not add `setGovernance` method as we will be using `SafeOwnable` and can just make Governance as the Owner.
* The `ITransferHook` is to be used for restricting/un-restricting of transfers.
=> feat: adding interfaces for PPO and TransferHook

apps/smart-contracts/token/contracts/interfaces/IAllowList.sol
* Adding `IAllowlist` interface.
* This contract will have the functionality to add and remove the list of addresses to allowed sources and destinations.
* Also, `resetDestination` and `resetSources` will follow a logic similar to the one implemented in one of the core dapp [contracts](https://github.com/prepo-io/prepo-monorepo/blob/fae573c0bf17b36628ce0fc5e0cf21f4b594659d/apps/smart-contracts/core/contracts/AccountAccessController.sol#L21).
=> feat: adding interface for allow list for ppo contract

apps/smart-contracts/token/contracts/interfaces/IBlockList.sol
* Adding `IBlockList` interface.
* This contract will provide the functionality to block and unblock accounts from transferring PPO.
* Also, `reset()` will follow a logic similar to the one implemented in one of the core dapp [contract](https://github.com/prepo-io/prepo-monorepo/blob/fae573c0bf17b36628ce0fc5e0cf21f4b594659d/apps/smart-contracts/core/contracts/AccountAccessController.sol#L21).
=> feat: adding interface for block list for ppo contract

packages/prepo-shared-contracts/contracts/SafeOwnableUpgradeable.sol, packages/prepo-shared-contracts/contracts/mock/DeployableSafeOwnableUpgradeable.sol, packages/prepo-shared-contracts/test/SafeOwnableUpgradeable.test.ts, packages/prepo-shared-contracts/test/fixtures/DeployableSafeOwnableUpgradeableFixture.ts, packages/prepo-shared-contracts/test/fixtures/SafeOwnableUpgradeableFixture.ts
So, while I originally wrote `SafeOwnableUpgradeable` to conform to the convention of `SafeOwnable`, where the contract is not `abstract`, and thus can be delployed without a wrapper contract, there are minor problems that this introduces that I don't think are worth designing around just because we don't want mock or wrapper contracts.
How OpenZeppelin designs upgradeable contracts is that they are not to be initialized at all via the constructor, and are to be initialized afterwards in using a special kind of `initializer` function. `initializer` functions may only be called once, so you can't embed a parent `initializer` function call into your own `initializer` call (it works similar to `ReentrancyGuard`, you can't call a `nonReentrant` function within a `nonReentrant` function …
=> fix: make SafeOwnableUpgradeable abstract to conform to upgradeable contract convention

apps/smart-contracts/token/contracts/Blocklist.sol, apps/smart-contracts/token/contracts/interfaces/IBlocklist.sol, apps/smart-contracts/token/test/Blocklist.test.ts
* initialized Blocklist with nominee set in the constructor.
* Also added `_blockedAccountsIndex`, which will be used when resetting the blocklist by incrementing the index.
* Following nested mapping is used to keep track of the blocklist:
`mapping(uint256 => mapping(address => bool)) private _blockedAccounts;`
* Tests for covering `isAccountBlocked` will be added in the subsequent PR when inside the tests for setting up the blocklist.
=> feat: initialized blocklist and base state

apps/smart-contracts/token/contracts/AccountList.sol, apps/smart-contracts/token/test/AccountList.test.ts
Tests were taken from the old `Blocklist.test.ts`, except with a modification to the `sets lattermost bool value...` test.
The old test starts with the account not being included, and the latter most value is also false, so there will effectively be no change. I have made it start with the account to be included so there is a change to be reflected.
=> feat: added set and reset implementations

apps/smart-contracts/token/contracts/BlocklistTransferHook.sol, apps/smart-contracts/token/test/BlocklistTransferHook.test.ts
* Adding logic for `hook` of `BlocklistTransferHook`.
* The `hook` checks for the criteria that neither the source nor destination should be on the blocklist.
=> feat: adding unrestricted transfer hook logic

apps/smart-contracts/core/hardhat.config.ts, apps/smart-contracts/token/hardhat.config.ts, packages/prepo-constants/src/networks.ts, packages/prepo-hardhat/src/generateHardhatConfig.ts, packages/prepo-hardhat/src/generateHardhatLocalConfig.ts
We need to add support for Arbitrum and Arbitrum One networks to prepare for our token launch. 
I decided to remove specifying `optimisticEthereum` api keys because we don't even have a `Network` definition for Optimism in our shared constants package and are not even using Optimism.
I have renamed our network definition for `mumbai` to `polygonMumbai`, to rationalize the naming with the`@nomiclabs/hardhat-etherscan` library.
=> feat: add arbitrum networks, rationalize names for relevant networks

apps/smart-contracts/token/contracts/BlocklistTransferHook.sol, apps/smart-contracts/token/contracts/RestrictedTransferHook.sol, apps/smart-contracts/token/test/RestrictedTransferHook.test.ts
* Changed the inheritance, so that `RestrictedTransferHook` can inherit `BlocklistTransferHook` and use its functions internally.
* Since we also need to call `super.hook()`, it meant changing the visibility of `hook` in `BlocklistTransferHook` from `external` to `public` so that it could be called internally.
* Also as we were overriding the `hook`, and it is inherited from both `ITransferHook` and `BlocklistTransferHook` hence had to specify the overriding and at the same time convert the hook function in `BlocklistTransferHook` to virtual so that it can be overridden.
Note:
There was not a strict need to convert the `hook` of `RestrictedTransferHook` to virtual but I have done so to have the flexibility of inheriting and overriding in child contract in case if we want to extend in …
=> feat: changed inheritance order of transfer hooks

apps/smart-contracts/token/contracts/TokenShop.sol, apps/smart-contracts/token/contracts/Vesting.sol, apps/smart-contracts/token/contracts/interfaces/ITokenShop.sol, apps/smart-contracts/token/contracts/interfaces/IVesting.sol, apps/smart-contracts/token/test/TokenShop.test.ts, apps/smart-contracts/token/test/Vesting.test.ts
* Switching to shared `Pausable.sol` for token contracts.
* Also removed tests for `setPaused()`
=> feat: switching to shared pausable contract

apps/smart-contracts/token/contracts/TokenShop.sol, apps/smart-contracts/token/contracts/Vesting.sol, apps/smart-contracts/token/contracts/interfaces/ITokenShop.sol, apps/smart-contracts/token/contracts/interfaces/IVesting.sol, apps/smart-contracts/token/test/TokenShop.test.ts, apps/smart-contracts/token/test/Vesting.test.ts, packages/prepo-shared-contracts/contracts/Pausable.sol, packages/prepo-shared-contracts/contracts/interfaces/IPausable.sol, packages/prepo-shared-contracts/contracts/mock/PausableWrapper.sol, packages/prepo-shared-contracts/test/Pausable.test.ts, packages/prepo-shared-contracts/test/fixtures/PausableWrapperFixture.ts
* Adding files for the generic shared pausable contracts to be used by other contracts for setting `paused` and using the inherited modifier `whenNotPaused`.
* To add a test for the modifier, I had to create a wrapper around `Pausable.sol`. The wrapper `PausableWrapper.sol` only has one function, `testWhenNotPaused` with the modifier `whenNotPaused`.
* The contract `Pausable.sol` itself inherits from `SafeOwnable` without any constructor arguments, so by default, the `nominee` for `Pausable.sol` will be `ZERO_ADDRESS`, and the `owner` will be `deployer`.  But when the contract is inherited by any other contract, the `nominee` and `owner` will be of the inheriting contracts.
=> feat: adding shared Pausable with setters
